### ISSUE TITLE
docker-compose dev

### ISSUE THREAD

**Issue by yoowonyoung** [yoowonyoung/yoowonyoung.github.io#13]
```
version: "2.2"
services:
  postgres:
    image: postgres:12.3
    restart: always
    volumes:
      - ${PWD}/storage/postgres/data:/var/lib/postgresql/data
      - ${PWD}/config/postgres/postgres.sql:/docker-entrypoint-initdb.d/901-postgres.sql
    expose:
      - ${POSTGRES_PORT}
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      http_proxy:
      https_proxy:
      no_proxy:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ${PWD}/storage/mysql/log:/var/log/mysql
      - ${PWD}/storage/mysql/lib:/var/lib/mysql
      #- ${PWD}/config/mysql/schema.sql:/docker-entrypoint-initdb.d/901-schema.sql
      - ${PWD}/config/mysql/staging.sql:/docker-entrypoint-initdb.d/902-staging.sql
    expose:
      - ${MYSQL_PORT}
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      http_proxy:
      https_proxy:
      no_proxy:
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  frontend:
    image: dev-dashboard-ui:dev
    build:
      context: ./config/fe/dev
      dockerfile: Dockerfile.dev
      args:
        http_proxy:
        https_proxy:
        no_proxy:
    init: true
    restart: always
    volumes:
      - ${PWD}/src/fe:/fe
      #- ${PWD}/config/fe/dev/proxy.conf.json:/fe/proxy.conf.json
      #- ${PWD}/config/fe/dev/environment.local.ts:/fe/src/environments/environment.local.ts
    working_dir: /fe
    expose:
      - 4200
    ports:
      - ${FE_PORT}:4200
    command: ['node_modules/@angular/cli/bin/ng', 'serve', '--proxy-config', 'proxy.docker.conf.json', '--environment', 'local', '--host', '0.0.0.0']
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
  backend:
    image: dev-dashboard:dev
    build:
      context: ./config/be/dev
      dockerfile: Dockerfile.dev
      args:
        http_proxy:
        https_proxy:
        no_proxy:
    init: true
    env_file:
      - .env
    restart: always
    volumes:
      - ${PWD}/src/be:/root
      #- ${PWD}/config/be/dev/application.dev.yaml:/root/src/main/resources/application.yaml
      #- ${PWD}/config/be/dev/onelogin.saml2.properties.develop:/root/src/main/resources/onelogin/onelogin.saml2.properties.develop
      - ${PWD}/storage/backend/m2:/root/.m2
    working_dir: /root
    depends_on:
      - mysql
      - postgres
    expose:
      - 8080
    #ports:
    #  - ${BE_PORT}:8080
    command: ['mvn', 'spring-boot:run']
```
