### ISSUE TITLE
docker compose prod

### ISSUE THREAD

**Issue by yoowonyoung** [yoowonyoung/yoowonyoung.github.io#14]
```
version: "2.2"
services:
  server:
    image: art.sec.samsung.net/rs7-swcdashboard_docker/dboard:${IMAGE_TAG}
    env_file:
      - .env
    depends_on:
      - mysql
    restart: always
    ports:
      - ${BE_PORT}:8080
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    restart: always
    volumes:
      - ./storage/mysql/log:/var/log/mysql
      - ./storage/mysql/lib:/var/lib/mysql
      #- ${PWD}/config/mysql/staging.sql:/docker-entrypoint-initdb.d/901-staging.sql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  postgres:
    image: postgres:12.3
    restart: always
    volumes:
      - ${PWD}/storage/postgres/data:/var/lib/postgresql/data
      #- ${PWD}/config/postgres/postgres.sql:/docker-entrypoint-initdb.d/901-postgres.sql
    expose:
      - ${POSTGRES_PORT}
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      http_proxy:
      https_proxy:
      no_proxy:
```
