### ISSUE TITLE
Deploy Playbook

### ISSUE THREAD

**Issue by yoowonyoung** [yoowonyoung/yoowonyoung.github.io#18]
```
---

- name: Setup dboard
  hosts:
    - dboard_stg
    - dboard_prod
  become: yes

  tasks:
    - name: Create dboard workspace
      file:
        state: directory
        path: "{{ workspace }}"
        mode: 0755
      notify: restart service

    - name: Copy empty DB Dump
      template:
        src: ../files/common/dump.sql
        dest: "{{ workspace }}/dump.sql"
        mode: 0644
      notify: restart service
      when: dbdump_filename == ""

    - name: Download DB Dump
      get_url:
        url: "{{ artifactory_url }}/{{ artifactory_generic_repo }}/{{ artifactory_dboard_db_backup_path}}/{{ dbdump_filename }}"
        dest: "{{ workspace }}/dump.sql"
        username: "{{ artifactory_auth_username }}"
        password: "{{ artifactory_auth_password }}"
        force: true
      notify: restart service
      when: dbdump_filename != ""

    - name: Clean DB Storage
      file:
        path: "{{ workspace }}/storage"
        state: absent
      notify: restart service
      when: dbdump_filename != ""

    - name: Copy docker-compose.yml template
      template:
        src: "{{ docker_compose_template_path }}"
        dest: "{{ workspace }}/docker-compose.yml"
        mode: 0644
      notify: restart service

    - name: Copy .env template
      template:
        src: "{{ env_template_path }}"
        dest: "{{ workspace }}/.env"
        mode: 0644
      notify: restart service

    - name: Login docker registry
      docker_login:
        username: "{{ artifactory_auth_username }}"
        password: "{{ artifactory_auth_password }}"
        registry: "{{ docker_registry_url }}"
      notify: restart service

  handlers:
    - name: run docker-compose
      command: docker-compose up --force-recreate -d
      args:
        chdir: "{{ workspace }}"
      listen: restart service
```

**Comment by yoowonyoung** [comment]
```
---

- name: Stop dboard
  hosts:
    - dboard_stg
    - dboard_prod
    - dcube_stg
    - dcube_prod
  become: yes

  tasks:
    - name: docker-compose up
      command: docker-compose up --force-recreate -d
      args:
        chdir: "{{ workspace }}"


```

**Comment by yoowonyoung** [comment]
Stop Docker

```
---

- name: Stop dboard
  hosts:
    - dboard_stg
    - dboard_prod
    - dcube_stg
    - dcube_prod
  become: yes

  tasks:
    - name: docker-compose down
      command: docker-compose down
      args:
        chdir: "{{ workspace }}"

```
